### ISSUE TITLE
add Header to Response

### ISSUE THREAD

**Issue by zhyon404** [chyroc/lark#12]
when request file, i wan;t to know type of file. it would be helpful if we can get `Content-Type` of `header`. so can we expose header to the user?
```
	a, rsp, c := cli.Message.GetMessageFile(ctx, req)
	t.Log(rsp.Heads.Get("Content-Type"))
```

**Comment by chyroc** [comment]
No problem, I just saw this. It will be realized tomorrow. You can join readme's lark group chat for real-time help.

**Comment by chyroc** [comment]
https://github.com/chyroc/lark/pull/13

**Comment by chyroc** [comment]
@zhyon404 hi, release v0.0.49
