### ISSUE TITLE
invalid memory address or nil pointer

### ISSUE THREAD

**Issue by hodgekou** [chyroc/lark#33]
**Describe the bug**
GOHOSTARCH="amd64"
GOHOSTOS="linux"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x66eb58]

func (r *MessageService) SendRawMessage(ctx context.Context, request *SendRawMessageReq, options ...MethodOptionFunc) (*SendRawMessageResp, *Response, error) 

** OK **
Darwin is ok

**Comment by chyroc** [comment]
@hodgekou please upload panic stack log for debug
