### ISSUE TITLE
Demo 问题

### ISSUE THREAD

**Issue by jinyu121** [chyroc/lark#58]
## 问题

https://github.com/chyroc/lark/blob/master/_examples/event_callback.go#L47 这里永远会走「收到了一条纯文本消息」的逻辑。

## 原因

https://github.com/chyroc/lark/blob/master/_examples/event_callback.go#L42 函数 [UnwrapMessageContent](https://github.com/chyroc/lark/blob/b1327ddeaf6ed96bccea8a0a181087e99efd8f3c/helper.go#L64)已经将所有东西都实例化了，都不为nil，所以在判断content.XXX为空的时候，不能用nil来进行判断，只能用 `""==content.XXX.XXX`、`0==len(content.XXX.XXX)`来判空，稍微麻烦一丢丢。

## 影响版本

[v0.0.96](https://github.com/chyroc/lark/releases/tag/v0.0.96) 及以下

## 个人建议

`UnwrapMessageContent` 里面全用空指针初始化？使用起来也方便一点。

**Comment by chyroc** [comment]
你好，确实有这个问题。
请问你是否方便创建一个 pull request 来修复这个问题。
如果你可以的话，非常感谢，否则我将修复这个问题。

**Comment by chyroc** [comment]
fixed by https://github.com/chyroc/lark/pull/59, close.
