### ISSUE TITLE
建议根据模块进行一些文件分组，现在都在根目录阅读有些困难

### ISSUE THREAD

**Issue by biukang** [chyroc/lark#62]
建议根据模块进行一些文件分组，现在都在根目录阅读有些困难

**Comment by chyroc** [comment]
1、因为包名都是 lark，所以导致不能创建一个文件夹来放文件
2、曾经尝试过合并文件，但是单文件太大，导致有些人打不开这些文件

**Comment by chyroc** [comment]
https://github.com/chyroc/lark/blob/74851503708edaca73e4142704e74bbfaf48b585/api_apis.merged.go

**Comment by biukang** [comment]
理解了，谢谢解答
